// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionAgricola.Data;

#nullable disable

namespace SistemaGestionAgricola.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107202216_CreateTipoInsumosTable")]
    partial class CreateTipoInsumosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Agricultor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Experiencia")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Agricultores");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Cultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("planificado");

                    b.Property<DateTime>("FechaCosechaEstimada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("date");

                    b.Property<int>("TerrenoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCultivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCosechaEstimada");

                    b.HasIndex("FechaSiembra");

                    b.HasIndex("TerrenoId");

                    b.HasIndex("TipoCultivoId");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.DetallePreparacionTerreno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("HorasMaquinaria")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPreparacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId");

                    b.ToTable("DetallesPreparacionTerreno");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.InsumoUtilizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostoFlete")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ProcesoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoInsumoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoId");

                    b.HasIndex("TipoInsumoId");

                    b.ToTable("InsumosUtilizados");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.ProcesoAgricola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoManoObra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("CultivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("TipoProcesoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CultivoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("TipoProcesoId");

                    b.ToTable("ProcesosAgricolas");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Terreno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgricultorId")
                        .HasColumnType("int");

                    b.Property<decimal>("AreaHectareas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostoAlquiler")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoTenencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId");

                    b.ToTable("Terrenos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoCultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("InstruccionesFumigaciones")
                        .HasColumnType("text");

                    b.Property<string>("InstruccionesRiegos")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TiempoSiembraCosecha")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoCultivos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoInsumos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoProceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoProcesos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Agricultor", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.Usuario", "Usuario")
                        .WithOne("Agricultor")
                        .HasForeignKey("SistemaGestionAgricola.Models.Entities.Agricultor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Cultivo", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.Terreno", "Terreno")
                        .WithMany("Cultivos")
                        .HasForeignKey("TerrenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionAgricola.Models.Entities.TipoCultivo", "TipoCultivo")
                        .WithMany("Cultivos")
                        .HasForeignKey("TipoCultivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terreno");

                    b.Navigation("TipoCultivo");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.DetallePreparacionTerreno", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.ProcesoAgricola", "ProcesoAgricola")
                        .WithMany("DetallesPreparacionTerreno")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesoAgricola");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.InsumoUtilizado", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.ProcesoAgricola", "ProcesoAgricola")
                        .WithMany("InsumosUtilizados")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionAgricola.Models.Entities.TipoInsumo", "TipoInsumo")
                        .WithMany("InsumosUtilizados")
                        .HasForeignKey("TipoInsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcesoAgricola");

                    b.Navigation("TipoInsumo");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.ProcesoAgricola", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.Cultivo", "Cultivo")
                        .WithMany("ProcesosAgricolas")
                        .HasForeignKey("CultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionAgricola.Models.Entities.TipoProceso", "TipoProceso")
                        .WithMany("ProcesosAgricolas")
                        .HasForeignKey("TipoProcesoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cultivo");

                    b.Navigation("TipoProceso");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Terreno", b =>
                {
                    b.HasOne("SistemaGestionAgricola.Models.Entities.Agricultor", "Agricultor")
                        .WithMany("Terrenos")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Agricultor", b =>
                {
                    b.Navigation("Terrenos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Cultivo", b =>
                {
                    b.Navigation("ProcesosAgricolas");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.ProcesoAgricola", b =>
                {
                    b.Navigation("DetallesPreparacionTerreno");

                    b.Navigation("InsumosUtilizados");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Terreno", b =>
                {
                    b.Navigation("Cultivos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoCultivo", b =>
                {
                    b.Navigation("Cultivos");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoInsumo", b =>
                {
                    b.Navigation("InsumosUtilizados");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.TipoProceso", b =>
                {
                    b.Navigation("ProcesosAgricolas");
                });

            modelBuilder.Entity("SistemaGestionAgricola.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Agricultor");
                });
#pragma warning restore 612, 618
        }
    }
}
